version: '3.8'

services:
  # Основной API сервер
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: wbsimple_api
    restart: always
    ports:
      - "5005:5005"
    volumes:
      - ./server/logs:/app/logs
      - ./server/uploads:/app/uploads
    env_file:
      - ./server/.env.production
    depends_on:
      - postgres
      - redis
    networks:
      - wbsimple_network

  # Веб-интерфейс на Next.js
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: wbsimple_web
    restart: always
    ports:
      - "80:3000"
    env_file:
      - ./client/.env.production
    depends_on:
      - api
    networks:
      - wbsimple_network

  # База данных PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: wbsimple_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=wbsimple
      - POSTGRES_PASSWORD=wbsimple
      - POSTGRES_DB=wbsimple
    networks:
      - wbsimple_network

  # Redis для кэширования
  redis:
    image: redis:alpine
    container_name: wbsimple_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wbsimple_network

networks:
  wbsimple_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 